name = "r2-backup-worker"
main = "r2-backup-worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# 环境变量配置（占位符，防止部署时被删除）
# 实际值请在 Cloudflare Dashboard 的环境变量中设置
[vars]
AUTH_TOKEN = ""  # 请在 Dashboard 设置真实值
ALLOWED_ORIGINS = "https://www.nodeseek.com,https://www.deepflood.com"

# R2 存储绑定（占位符，防止部署时被删除）
# 实际绑定请在 Cloudflare Dashboard 中配置
[[r2_buckets]]
binding = "R2_BUCKET"
bucket_name = ""  # 请在 Dashboard 绑定实际的 R2 存储桶