name = "r2-backup-worker"
main = "r2-backup-worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]


# 这些变量不要直接写在这里，推荐在 Dashboard 的 Worker 设置中配置

# R2 存储绑定（推荐使用）
# [[r2_buckets]]
# binding = "R2_BUCKET"
# bucket_name = "your-r2-bucket-name"

# 环境变量配置示例（在 Cloudflare Dashboard 中配置）
# [vars]

# 必需配置：
# AUTH_TOKEN = "your-secret-token-here"
# ALLOWED_ORIGINS = "https://www.nodeseek.com,https://www.deepflood.com"

# S3 兼容存储配置（可选，仅在不使用 R2 绑定时）：
# S3_ENDPOINT = "https://cos.ap-guangzhou.myqcloud.com"
# S3_REGION = "ap-guangzhou"
# S3_BUCKET = "my-backup-bucket"
# S3_ACCESS_KEY_ID = "AKIDxxxxx"
# S3_SECRET_ACCESS_KEY = "xxxxxx"
# S3_PATH_STYLE = "false"  # MinIO 设为 "true"